# Ansible playbook AWS - install docker
---
    - name: "AWS - Install docker"
      hosts: localhost
#become: yes assumes the unix user that is running ansible has sudo access
      become: yes
      tasks:
        - name: Update all packages
          yum:
            name: '*'
            state: latest
            update_only: yes
    
        - name: Ensure a list of yum packages are installed
          yum:
            name: "{{ packages }}"
            state: latest
            update_cache: yes
          vars:
            packages:
            - yum-utils
            - device-mapper-persistent-data
            - lvm2

#requirement for the docker_container ansible component
        - pip:
            name:
              - docker
    
        - name: Add extras repository
          shell: yum-config-manager --enable extras
    
        - name: Install docker-ce (centos) via amazon-linux-extras packages
          shell: "amazon-linux-extras install docker -y"

        - name: Enable Docker CE service at startup
          service:
            name: docker
            state: started
            enabled: yes

#Pulls and starts the specified docker container. Technical does not need to start it.
        - name: Start container
          docker_container:
            name: honeypot
            image: liamwadman/forever200:latest
            ports:
              - "80:80"

...
